package com.chna.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * An immutable audit trail entry generated by Filter 3 (Logique Métier & Smart Cache).
 * Per doc.md §3.5.4 and the "Maintain Audit Trail" tactic, every access to medical data
 * MUST generate a non-repudiable, timestamped entry. In the prototype, these are displayed
 * in real-time on the Audit Trail sidebar.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class AuditEntry {
    /** ISO-8601 timestamp of the event */
    private String timestamp;

    /** The node that performed the action (e.g. "Nœud A", "Nœud B") */
    private String noeud;

    /** The filter ID that generated this entry (1–4) */
    private int filterId;

    /** Pipeline number (1, 2, or 3) */
    private int pipeline;

    /** Human-readable description of the action */
    private String action;

    /** The patient identifier involved */
    private String patientId;
}