package com.chna.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Standardized FHIR R4 resource returned by Node B after translation.
 * Produced by Filter 1 (Adaptateur FHIR / Anti-Corruption Layer, doc.md §3.5.2).
 * This is what travels on the mTLS P2P channel and is displayed on Node A's timeline.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class FhirResponse {
    /** FHIR R4 resource type (e.g. "DiagnosticReport") */
    private String resourceType;

    /** Internal FHIR ID */
    private String id;

    /** FHIR R4 status code (e.g. "final") */
    private String status;

    /** SNOMED CT or LOINC code identifying the observation category */
    private String code;

    /** Display label for the medical section */
    private String display;

    /** IPN of the subject patient (National Patient Identifier) */
    private String subjectId;

    /** The translated medical conclusion (human-readable) */
    private String conclusion;

    /** ISO-8601 timestamp of the original exam */
    private String effectiveDateTime;

    /** Identifier of the originating node (détenteur) */
    private String sourceNode;

    /** Audit trail entry generated by Filter 3 on reception */
    private AuditEntry auditEntry;
}